"""Add WhatsApp-ready omnichannel inbox.

Revision ID: 0006_inbox
Revises: 0005_conversations
"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0006_inbox";down_revision:str|None="0005_conversations";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("channels",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("kind",sa.String(30),nullable=False),sa.Column("external_key",sa.String(120),nullable=False),sa.Column("webhook_secret_hash",sa.String(64),nullable=False),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","external_key"));op.create_index("ix_channels_organization_id","channels",["organization_id"]);op.create_index("ix_channels_external_key","channels",["external_key"],unique=True)
    op.create_table("contacts",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("phone",sa.String(30),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","phone"));op.create_index("ix_contacts_organization_id","contacts",["organization_id"])
    op.create_table("inbox_threads",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("channel_id",sa.Uuid(),sa.ForeignKey("channels.id",ondelete="CASCADE"),nullable=False),sa.Column("contact_id",sa.Uuid(),sa.ForeignKey("contacts.id",ondelete="CASCADE"),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("unread_count",sa.Integer(),nullable=False),sa.Column("last_message_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("channel_id","contact_id"));op.create_index("ix_inbox_threads_organization_id","inbox_threads",["organization_id"]);op.create_index("ix_inbox_threads_channel_id","inbox_threads",["channel_id"]);op.create_index("ix_inbox_threads_contact_id","inbox_threads",["contact_id"]);op.create_index("ix_inbox_thread_tenant_status","inbox_threads",["organization_id","status"])
    op.create_table("channel_messages",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("channel_id",sa.Uuid(),sa.ForeignKey("channels.id",ondelete="CASCADE"),nullable=False),sa.Column("thread_id",sa.Uuid(),sa.ForeignKey("inbox_threads.id",ondelete="CASCADE"),nullable=False),sa.Column("external_message_id",sa.String(160),nullable=False),sa.Column("direction",sa.String(20),nullable=False),sa.Column("content",sa.Text(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("channel_id","external_message_id"));op.create_index("ix_channel_messages_organization_id","channel_messages",["organization_id"]);op.create_index("ix_channel_messages_channel_id","channel_messages",["channel_id"]);op.create_index("ix_channel_messages_thread_id","channel_messages",["thread_id"]);op.create_index("ix_channel_message_tenant_thread","channel_messages",["organization_id","thread_id"])
def downgrade()->None:op.drop_table("channel_messages");op.drop_table("inbox_threads");op.drop_table("contacts");op.drop_table("channels")
