"""Add purchases and inventory.

Revision ID: 0014_inventory_purchases
Revises: 0013_hr
"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0014_inventory_purchases";down_revision:str|None="0013_hr";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("suppliers",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("email",sa.String(255)),sa.Column("phone",sa.String(30)),sa.Column("status",sa.String(30),nullable=False,server_default="active"),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_suppliers_organization_id","suppliers",["organization_id"]);op.create_index("ix_supplier_tenant_status","suppliers",["organization_id","status"])
    op.create_table("products",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("sku",sa.String(80),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("unit",sa.String(20),nullable=False,server_default="un"),sa.Column("quantity",sa.Integer(),nullable=False,server_default="0"),sa.Column("minimum_stock",sa.Integer(),nullable=False,server_default="0"),sa.Column("unit_cost_cents",sa.Integer(),nullable=False,server_default="0"),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","sku"));op.create_index("ix_products_organization_id","products",["organization_id"]);op.create_index("ix_product_tenant_active","products",["organization_id","active"])
    op.create_table("stock_movements",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("product_id",sa.Uuid(),sa.ForeignKey("products.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("movement_type",sa.String(30),nullable=False),sa.Column("quantity_delta",sa.Integer(),nullable=False),sa.Column("reason",sa.String(240),nullable=False),sa.Column("idempotency_key",sa.String(180)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","idempotency_key"));op.create_index("ix_stock_movements_organization_id","stock_movements",["organization_id"]);op.create_index("ix_stock_movements_product_id","stock_movements",["product_id"]);op.create_index("ix_stock_movements_created_by","stock_movements",["created_by"]);op.create_index("ix_stock_movement_tenant_product","stock_movements",["organization_id","product_id"])
    op.create_table("purchase_orders",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("supplier_id",sa.Uuid(),sa.ForeignKey("suppliers.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("status",sa.String(30),nullable=False,server_default="draft"),sa.Column("total_cents",sa.Integer(),nullable=False,server_default="0"),sa.Column("expected_at",sa.Date()),sa.Column("received_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_purchase_orders_organization_id","purchase_orders",["organization_id"]);op.create_index("ix_purchase_orders_supplier_id","purchase_orders",["supplier_id"]);op.create_index("ix_purchase_orders_created_by","purchase_orders",["created_by"]);op.create_index("ix_purchase_order_tenant_status","purchase_orders",["organization_id","status"])
    op.create_table("purchase_order_items",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("purchase_order_id",sa.Uuid(),sa.ForeignKey("purchase_orders.id",ondelete="CASCADE"),nullable=False),sa.Column("product_id",sa.Uuid(),sa.ForeignKey("products.id",ondelete="RESTRICT"),nullable=False),sa.Column("quantity",sa.Integer(),nullable=False),sa.Column("unit_cost_cents",sa.Integer(),nullable=False),sa.Column("total_cents",sa.Integer(),nullable=False));op.create_index("ix_purchase_order_items_organization_id","purchase_order_items",["organization_id"]);op.create_index("ix_purchase_order_items_purchase_order_id","purchase_order_items",["purchase_order_id"]);op.create_index("ix_purchase_order_items_product_id","purchase_order_items",["product_id"])
def downgrade()->None:
    op.drop_table("purchase_order_items");op.drop_table("purchase_orders");op.drop_table("stock_movements");op.drop_table("products");op.drop_table("suppliers")
