"""Add public API, webhooks and white label.

Revision ID: 0015_platform_api
Revises: 0014_inventory_purchases
"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0015_platform_api";down_revision:str|None="0014_inventory_purchases";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("api_keys",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(120),nullable=False),sa.Column("prefix",sa.String(20),nullable=False),sa.Column("secret_hash",sa.String(64),nullable=False,unique=True),sa.Column("scopes",sa.JSON(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("last_used_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_api_keys_organization_id","api_keys",["organization_id"]);op.create_index("ix_api_keys_created_by","api_keys",["created_by"]);op.create_index("ix_api_key_tenant_active","api_keys",["organization_id","active"])
    op.create_table("webhook_endpoints",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(120),nullable=False),sa.Column("url",sa.String(1000),nullable=False),sa.Column("secret",sa.String(120),nullable=False),sa.Column("events",sa.JSON(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_webhook_endpoints_organization_id","webhook_endpoints",["organization_id"]);op.create_index("ix_webhook_endpoints_created_by","webhook_endpoints",["created_by"]);op.create_index("ix_webhook_endpoint_tenant_active","webhook_endpoints",["organization_id","active"])
    op.create_table("webhook_deliveries",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("endpoint_id",sa.Uuid(),sa.ForeignKey("webhook_endpoints.id",ondelete="CASCADE"),nullable=False),sa.Column("event_type",sa.String(100),nullable=False),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="queued"),sa.Column("attempts",sa.Integer(),nullable=False,server_default="0"),sa.Column("last_error",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("delivered_at",sa.DateTime(timezone=True)));op.create_index("ix_webhook_deliveries_organization_id","webhook_deliveries",["organization_id"]);op.create_index("ix_webhook_deliveries_endpoint_id","webhook_deliveries",["endpoint_id"]);op.create_index("ix_webhook_delivery_tenant_status","webhook_deliveries",["organization_id","status"])
    op.create_table("organization_branding",sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),primary_key=True),sa.Column("product_name",sa.String(120),nullable=False,server_default="OperAI"),sa.Column("primary_color",sa.String(7),nullable=False,server_default="#6c5ce7"),sa.Column("logo_url",sa.String(1000)),sa.Column("support_email",sa.String(255)),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
def downgrade()->None:
    op.drop_table("organization_branding");op.drop_table("webhook_deliveries");op.drop_table("webhook_endpoints");op.drop_table("api_keys")
