"""Add agent marketplace and installations.

Revision ID: 0016_agent_marketplace
Revises: 0015_platform_api
"""
from collections.abc import Sequence
import sqlalchemy as sa
import uuid
from alembic import op
revision:str="0016_agent_marketplace";down_revision:str|None="0015_platform_api";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("agent_templates",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("slug",sa.String(120),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("publisher",sa.String(120),nullable=False,server_default="OperAI"),sa.Column("category",sa.String(60),nullable=False),sa.Column("agent_type",sa.String(50),nullable=False),sa.Column("version",sa.String(30),nullable=False,server_default="1.0.0"),sa.Column("description",sa.Text(),nullable=False),sa.Column("instructions_template",sa.Text(),nullable=False),sa.Column("icon",sa.String(20),nullable=False,server_default="◎"),sa.Column("price_cents",sa.Integer(),nullable=False,server_default="0"),sa.Column("published",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("slug","version"));op.create_index("ix_agent_template_published_category","agent_templates",["published","category"])
    op.create_table("agent_installations",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("template_id",sa.Uuid(),sa.ForeignKey("agent_templates.id",ondelete="RESTRICT"),nullable=False),sa.Column("agent_id",sa.Uuid(),sa.ForeignKey("agents.id",ondelete="CASCADE"),nullable=False),sa.Column("installed_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("installed_version",sa.String(30),nullable=False),sa.Column("configuration",sa.JSON(),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="active"),sa.Column("installed_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","template_id"));op.create_index("ix_agent_installations_organization_id","agent_installations",["organization_id"]);op.create_index("ix_agent_installations_template_id","agent_installations",["template_id"]);op.create_index("ix_agent_installations_agent_id","agent_installations",["agent_id"]);op.create_index("ix_agent_installations_installed_by","agent_installations",["installed_by"]);op.create_index("ix_agent_installation_tenant_status","agent_installations",["organization_id","status"])
    templates=sa.table("agent_templates",sa.column("id",sa.Uuid()),sa.column("slug",sa.String()),sa.column("name",sa.String()),sa.column("publisher",sa.String()),sa.column("category",sa.String()),sa.column("agent_type",sa.String()),sa.column("version",sa.String()),sa.column("description",sa.Text()),sa.column("instructions_template",sa.Text()),sa.column("icon",sa.String()),sa.column("price_cents",sa.Integer()),sa.column("published",sa.Boolean()))
    op.bulk_insert(templates,[
        {"id":uuid.UUID("10000000-0000-0000-0000-000000000001"),"slug":"sdr-autonomo","name":"SDR Autônomo","publisher":"OperAI","category":"Vendas","agent_type":"commercial","version":"1.0.0","description":"Qualifica leads, prioriza oportunidades e organiza follow-ups comerciais.","instructions_template":"Atue como SDR B2B. Qualifique cada lead, identifique dor, urgência e orçamento, e proponha a próxima ação comercial com objetividade.","icon":"◈","price_cents":0,"published":True},
        {"id":uuid.UUID("10000000-0000-0000-0000-000000000002"),"slug":"cobranca-inteligente","name":"Cobrança Inteligente","publisher":"OperAI","category":"Financeiro","agent_type":"billing","version":"1.0.0","description":"Prioriza inadimplência e prepara abordagens de cobrança contextualizadas.","instructions_template":"Atue como especialista de cobrança respeitosa. Priorize vencidos por risco e valor, personalize a comunicação e registre todas as ações.","icon":"$","price_cents":0,"published":True},
        {"id":uuid.UUID("10000000-0000-0000-0000-000000000003"),"slug":"analista-bi","name":"Analista de BI","publisher":"OperAI","category":"Dados","agent_type":"bi","version":"1.0.0","description":"Consolida indicadores e transforma dados operacionais em decisões.","instructions_template":"Atue como analista de negócios. Explique indicadores, identifique tendências, anomalias e causas prováveis, e recomende ações mensuráveis.","icon":"▦","price_cents":0,"published":True},
        {"id":uuid.UUID("10000000-0000-0000-0000-000000000004"),"slug":"repositor-estoque","name":"Repositor de Estoque","publisher":"OperAI","category":"Operações","agent_type":"inventory","version":"1.0.0","description":"Monitora ruptura, calcula reposição e acompanha pedidos de compra.","instructions_template":"Atue como analista de estoque. Monitore níveis mínimos, estime reposição com segurança e acompanhe pedidos até o recebimento.","icon":"▥","price_cents":0,"published":True},
        {"id":uuid.UUID("10000000-0000-0000-0000-000000000005"),"slug":"customer-success","name":"Customer Success","publisher":"OperAI","category":"Clientes","agent_type":"success","version":"1.0.0","description":"Acompanha clientes, detecta risco de churn e organiza planos de sucesso.","instructions_template":"Atue como gerente de sucesso do cliente. Monitore engajamento, detecte riscos, organize planos de ação e maximize valor percebido.","icon":"♡","price_cents":0,"published":True},
        {"id":uuid.UUID("10000000-0000-0000-0000-000000000006"),"slug":"recrutador-ai","name":"Recrutador AI","publisher":"OperAI","category":"RH","agent_type":"hr","version":"1.0.0","description":"Apoia triagem, onboarding e acompanhamento de colaboradores.","instructions_template":"Atue como especialista de RH. Estruture triagens justas, onboarding, acompanhamento e registros com confidencialidade e critérios objetivos.","icon":"♧","price_cents":0,"published":True}
    ])
def downgrade()->None:
    op.drop_table("agent_installations");op.drop_table("agent_templates")
