"""Add SaaS plans, subscriptions and usage counters.

Revision ID: 0017_saas_billing
Revises: 0016_agent_marketplace
"""
from collections.abc import Sequence
from datetime import date,timedelta
import uuid
import sqlalchemy as sa
from alembic import op
revision:str="0017_saas_billing";down_revision:str|None="0016_agent_marketplace";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("saas_plans",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("slug",sa.String(50),nullable=False,unique=True),sa.Column("name",sa.String(80),nullable=False),sa.Column("monthly_price_cents",sa.Integer(),nullable=False),sa.Column("limits",sa.JSON(),nullable=False),sa.Column("features",sa.JSON(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("sort_order",sa.Integer(),nullable=False,server_default="0"));op.create_index("ix_saas_plans_slug","saas_plans",["slug"],unique=True)
    op.create_table("organization_subscriptions",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False,unique=True),sa.Column("plan_id",sa.Uuid(),sa.ForeignKey("saas_plans.id",ondelete="RESTRICT"),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="trialing"),sa.Column("current_period_start",sa.Date(),nullable=False),sa.Column("current_period_end",sa.Date(),nullable=False),sa.Column("cancel_at_period_end",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_organization_subscriptions_organization_id","organization_subscriptions",["organization_id"],unique=True);op.create_index("ix_organization_subscriptions_plan_id","organization_subscriptions",["plan_id"])
    op.create_table("usage_counters",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("period",sa.String(7),nullable=False),sa.Column("metric",sa.String(60),nullable=False),sa.Column("quantity",sa.Integer(),nullable=False,server_default="0"),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","period","metric"));op.create_index("ix_usage_counters_organization_id","usage_counters",["organization_id"])
    plans=sa.table("saas_plans",sa.column("id",sa.Uuid()),sa.column("slug",sa.String()),sa.column("name",sa.String()),sa.column("monthly_price_cents",sa.Integer()),sa.column("limits",sa.JSON()),sa.column("features",sa.JSON()),sa.column("active",sa.Boolean()),sa.column("sort_order",sa.Integer()))
    ids={"start":uuid.UUID("20000000-0000-0000-0000-000000000001"),"pro":uuid.UUID("20000000-0000-0000-0000-000000000002"),"business":uuid.UUID("20000000-0000-0000-0000-000000000003"),"enterprise":uuid.UUID("20000000-0000-0000-0000-000000000004")}
    op.bulk_insert(plans,[{"id":ids["start"],"slug":"start","name":"Start","monthly_price_cents":99700,"limits":{"agents":3,"users":5,"documents":100,"api_calls":10000},"features":["CRM","WhatsApp","Agenda","RAG"],"active":True,"sort_order":1},{"id":ids["pro"],"slug":"pro","name":"Pro","monthly_price_cents":249700,"limits":{"agents":10,"users":20,"documents":1000,"api_calls":100000},"features":["Todos do Start","Financeiro","Marketing","API"],"active":True,"sort_order":2},{"id":ids["business"],"slug":"business","name":"Business","monthly_price_cents":499700,"limits":{"agents":30,"users":100,"documents":10000,"api_calls":1000000},"features":["Todos do Pro","White-label","Marketplace","Webhooks"],"active":True,"sort_order":3},{"id":ids["enterprise"],"slug":"enterprise","name":"Enterprise","monthly_price_cents":1000000,"limits":{"agents":0,"users":0,"documents":0,"api_calls":0},"features":["Limites personalizados","SLA","Suporte dedicado"],"active":True,"sort_order":4}])
    subscriptions=sa.table("organization_subscriptions",sa.column("id",sa.Uuid()),sa.column("organization_id",sa.Uuid()),sa.column("plan_id",sa.Uuid()),sa.column("status",sa.String()),sa.column("current_period_start",sa.Date()),sa.column("current_period_end",sa.Date()),sa.column("cancel_at_period_end",sa.Boolean()))
    orgs=op.get_bind().execute(sa.text("SELECT id FROM organizations")).fetchall();today=date.today();op.bulk_insert(subscriptions,[{"id":uuid.uuid4(),"organization_id":row[0],"plan_id":ids["start"],"status":"trialing","current_period_start":today,"current_period_end":today+timedelta(days=14),"cancel_at_period_end":False} for row in orgs])
def downgrade()->None:
    op.drop_table("usage_counters");op.drop_table("organization_subscriptions");op.drop_table("saas_plans")
