"""Add customer success portfolio and interactions.

Revision ID: 0020_customer_success
Revises: 0019_webhook_dispatch
"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0020_customer_success";down_revision:str|None="0019_webhook_dispatch";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("customer_accounts",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("owner_user_id",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(180),nullable=False),sa.Column("email",sa.String(255),nullable=False),sa.Column("phone",sa.String(30)),sa.Column("lifecycle_stage",sa.String(30),nullable=False,server_default="onboarding"),sa.Column("mrr_cents",sa.Integer(),nullable=False,server_default="0"),sa.Column("started_on",sa.Date(),nullable=False),sa.Column("renewal_date",sa.Date()),sa.Column("health_score",sa.Integer(),nullable=False,server_default="70"),sa.Column("risk_level",sa.String(20),nullable=False,server_default="low"),sa.Column("last_contact_at",sa.DateTime(timezone=True)),sa.Column("notes",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","email"));op.create_index("ix_customer_accounts_organization_id","customer_accounts",["organization_id"]);op.create_index("ix_customer_accounts_owner_user_id","customer_accounts",["owner_user_id"]);op.create_index("ix_customer_account_tenant_risk","customer_accounts",["organization_id","risk_level"])
    op.create_table("customer_interactions",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("account_id",sa.Uuid(),sa.ForeignKey("customer_accounts.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("interaction_type",sa.String(30),nullable=False),sa.Column("sentiment",sa.String(20),nullable=False,server_default="neutral"),sa.Column("summary",sa.Text(),nullable=False),sa.Column("outcome",sa.String(240)),sa.Column("next_action",sa.String(240)),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_customer_interactions_organization_id","customer_interactions",["organization_id"]);op.create_index("ix_customer_interactions_account_id","customer_interactions",["account_id"]);op.create_index("ix_customer_interactions_created_by","customer_interactions",["created_by"]);op.create_index("ix_customer_interaction_tenant_account","customer_interactions",["organization_id","account_id"])
def downgrade()->None:
    op.drop_table("customer_interactions");op.drop_table("customer_accounts")
