"""Add governance approval policies and requests.

Revision ID: 0021_governance_approvals
Revises: 0020_customer_success
"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0021_governance_approvals";down_revision:str|None="0020_customer_success";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("approval_policies",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("action_type",sa.String(80),nullable=False),sa.Column("minimum_risk",sa.String(20),nullable=False,server_default="medium"),sa.Column("minimum_amount_cents",sa.Integer(),nullable=False,server_default="0"),sa.Column("required_role",sa.String(30),nullable=False,server_default="manager"),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","action_type"));op.create_index("ix_approval_policies_organization_id","approval_policies",["organization_id"])
    op.create_table("approval_requests",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("policy_id",sa.Uuid(),sa.ForeignKey("approval_policies.id",ondelete="SET NULL")),sa.Column("agent_task_id",sa.Uuid(),sa.ForeignKey("agent_tasks.id",ondelete="SET NULL")),sa.Column("requested_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("decided_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("action_type",sa.String(80),nullable=False),sa.Column("title",sa.String(180),nullable=False),sa.Column("description",sa.Text()),sa.Column("risk_level",sa.String(20),nullable=False,server_default="medium"),sa.Column("amount_cents",sa.Integer(),nullable=False,server_default="0"),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="pending"),sa.Column("decision_note",sa.Text()),sa.Column("expires_at",sa.DateTime(timezone=True)),sa.Column("decided_at",sa.DateTime(timezone=True)),sa.Column("executed_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_approval_requests_organization_id","approval_requests",["organization_id"]);op.create_index("ix_approval_requests_policy_id","approval_requests",["policy_id"]);op.create_index("ix_approval_requests_agent_task_id","approval_requests",["agent_task_id"]);op.create_index("ix_approval_requests_requested_by","approval_requests",["requested_by"]);op.create_index("ix_approval_requests_decided_by","approval_requests",["decided_by"]);op.create_index("ix_approval_request_tenant_status","approval_requests",["organization_id","status"])
def downgrade()->None:
    op.drop_table("approval_requests");op.drop_table("approval_policies")
