"""Add multi-agent workflows. Revision ID: 0023_multiagent_workflows Revises: 0022_agent_observability"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0023_multiagent_workflows";down_revision:str|None="0022_agent_observability";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("agent_workflows",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(160),nullable=False),sa.Column("description",sa.Text()),sa.Column("trigger_type",sa.String(40),nullable=False,server_default="manual"),sa.Column("status",sa.String(30),nullable=False,server_default="draft"),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","name"));op.create_index("ix_agent_workflows_organization_id","agent_workflows",["organization_id"]);op.create_index("ix_agent_workflows_created_by","agent_workflows",["created_by"]);op.create_index("ix_agent_workflow_tenant_status","agent_workflows",["organization_id","status"])
    op.create_table("agent_workflow_steps",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("workflow_id",sa.Uuid(),sa.ForeignKey("agent_workflows.id",ondelete="CASCADE"),nullable=False),sa.Column("agent_id",sa.Uuid(),sa.ForeignKey("agents.id",ondelete="SET NULL")),sa.Column("name",sa.String(160),nullable=False),sa.Column("action_type",sa.String(80),nullable=False),sa.Column("position",sa.Integer(),nullable=False),sa.Column("requires_approval",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("max_attempts",sa.Integer(),nullable=False,server_default="3"),sa.Column("configuration",sa.JSON(),nullable=False),sa.UniqueConstraint("workflow_id","position"));op.create_index("ix_agent_workflow_steps_organization_id","agent_workflow_steps",["organization_id"]);op.create_index("ix_agent_workflow_steps_workflow_id","agent_workflow_steps",["workflow_id"]);op.create_index("ix_agent_workflow_steps_agent_id","agent_workflow_steps",["agent_id"])
    op.create_table("agent_workflow_runs",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("workflow_id",sa.Uuid(),sa.ForeignKey("agent_workflows.id",ondelete="CASCADE"),nullable=False),sa.Column("started_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("status",sa.String(30),nullable=False,server_default="running"),sa.Column("current_position",sa.Integer(),nullable=False,server_default="1"),sa.Column("context",sa.JSON(),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)));op.create_index("ix_agent_workflow_runs_organization_id","agent_workflow_runs",["organization_id"]);op.create_index("ix_agent_workflow_runs_workflow_id","agent_workflow_runs",["workflow_id"]);op.create_index("ix_agent_workflow_runs_started_by","agent_workflow_runs",["started_by"]);op.create_index("ix_agent_workflow_run_tenant_status","agent_workflow_runs",["organization_id","status"])
def downgrade()->None:op.drop_table("agent_workflow_runs");op.drop_table("agent_workflow_steps");op.drop_table("agent_workflows")
