"""Add integration hub. Revision ID: 0024_integration_hub Revises: 0023_multiagent_workflows"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0024_integration_hub";down_revision:str|None="0023_multiagent_workflows";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("integration_connections",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(160),nullable=False),sa.Column("provider",sa.String(60),nullable=False),sa.Column("category",sa.String(40),nullable=False),sa.Column("base_url",sa.String(1000)),sa.Column("credentials_encrypted",sa.Text(),nullable=False),sa.Column("configuration",sa.JSON(),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="disconnected"),sa.Column("last_checked_at",sa.DateTime(timezone=True)),sa.Column("last_error",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","name"));op.create_index("ix_integration_connections_organization_id","integration_connections",["organization_id"]);op.create_index("ix_integration_connections_created_by","integration_connections",["created_by"]);op.create_index("ix_integration_connection_tenant_status","integration_connections",["organization_id","status"])
    op.create_table("integration_sync_runs",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("connection_id",sa.Uuid(),sa.ForeignKey("integration_connections.id",ondelete="CASCADE"),nullable=False),sa.Column("started_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("direction",sa.String(20),nullable=False,server_default="pull"),sa.Column("resource",sa.String(80),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="running"),sa.Column("records_read",sa.Integer(),nullable=False,server_default="0"),sa.Column("records_written",sa.Integer(),nullable=False,server_default="0"),sa.Column("error",sa.Text()),sa.Column("started_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)));op.create_index("ix_integration_sync_runs_organization_id","integration_sync_runs",["organization_id"]);op.create_index("ix_integration_sync_runs_connection_id","integration_sync_runs",["connection_id"]);op.create_index("ix_integration_sync_runs_started_by","integration_sync_runs",["started_by"]);op.create_index("ix_integration_sync_tenant_status","integration_sync_runs",["organization_id","status"])
def downgrade()->None:op.drop_table("integration_sync_runs");op.drop_table("integration_connections")
