"""Add intelligent model gateway. Revision ID: 0025_model_gateway Revises: 0024_integration_hub"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0025_model_gateway";down_revision:str|None="0024_integration_hub";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("llm_providers",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(120),nullable=False),sa.Column("provider",sa.String(40),nullable=False),sa.Column("model_name",sa.String(120),nullable=False),sa.Column("api_key_encrypted",sa.Text(),nullable=False),sa.Column("input_cost_micros_per_million",sa.Integer(),nullable=False,server_default="0"),sa.Column("output_cost_micros_per_million",sa.Integer(),nullable=False,server_default="0"),sa.Column("average_latency_ms",sa.Integer(),nullable=False,server_default="1000"),sa.Column("quality_score",sa.Integer(),nullable=False,server_default="75"),sa.Column("context_window",sa.Integer(),nullable=False,server_default="128000"),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","name"));op.create_index("ix_llm_providers_organization_id","llm_providers",["organization_id"]);op.create_index("ix_llm_providers_created_by","llm_providers",["created_by"]);op.create_index("ix_llm_provider_tenant_active","llm_providers",["organization_id","active"])
    op.create_table("model_routing_policies",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(160),nullable=False),sa.Column("task_type",sa.String(80),nullable=False),sa.Column("strategy",sa.String(30),nullable=False,server_default="balanced"),sa.Column("minimum_quality",sa.Integer(),nullable=False,server_default="60"),sa.Column("maximum_latency_ms",sa.Integer(),nullable=False,server_default="10000"),sa.Column("monthly_budget_cents",sa.Integer(),nullable=False,server_default="0"),sa.Column("fallback_enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","task_type"));op.create_index("ix_model_routing_policies_organization_id","model_routing_policies",["organization_id"]);op.create_index("ix_model_routing_policies_created_by","model_routing_policies",["created_by"])
    op.create_table("model_routing_decisions",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("policy_id",sa.Uuid(),sa.ForeignKey("model_routing_policies.id",ondelete="SET NULL")),sa.Column("provider_id",sa.Uuid(),sa.ForeignKey("llm_providers.id",ondelete="RESTRICT"),nullable=False),sa.Column("task_type",sa.String(80),nullable=False),sa.Column("estimated_input_tokens",sa.Integer(),nullable=False),sa.Column("estimated_output_tokens",sa.Integer(),nullable=False),sa.Column("estimated_cost_micros",sa.Integer(),nullable=False),sa.Column("score",sa.Integer(),nullable=False),sa.Column("reason",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_model_routing_decisions_organization_id","model_routing_decisions",["organization_id"]);op.create_index("ix_model_routing_decisions_policy_id","model_routing_decisions",["policy_id"]);op.create_index("ix_model_routing_decisions_provider_id","model_routing_decisions",["provider_id"]);op.create_index("ix_model_routing_decision_tenant_created","model_routing_decisions",["organization_id","created_at"])
def downgrade()->None:op.drop_table("model_routing_decisions");op.drop_table("model_routing_policies");op.drop_table("llm_providers")
