"""Add agent prompt studio. Revision ID: 0026_agent_studio Revises: 0025_model_gateway"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0026_agent_studio";down_revision:str|None="0025_model_gateway";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("agent_prompt_versions",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("agent_id",sa.Uuid(),sa.ForeignKey("agents.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("version",sa.Integer(),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("instructions",sa.Text(),nullable=False),sa.Column("change_note",sa.String(500),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="draft"),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("agent_id","version"));op.create_index("ix_agent_prompt_versions_organization_id","agent_prompt_versions",["organization_id"]);op.create_index("ix_agent_prompt_versions_agent_id","agent_prompt_versions",["agent_id"]);op.create_index("ix_agent_prompt_versions_created_by","agent_prompt_versions",["created_by"]);op.create_index("ix_agent_prompt_tenant_status","agent_prompt_versions",["organization_id","status"])
    op.create_table("agent_eval_cases",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("agent_id",sa.Uuid(),sa.ForeignKey("agents.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(160),nullable=False),sa.Column("input_text",sa.Text(),nullable=False),sa.Column("expected_behavior",sa.Text(),nullable=False),sa.Column("minimum_score",sa.Integer(),nullable=False,server_default="70"),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_agent_eval_cases_organization_id","agent_eval_cases",["organization_id"]);op.create_index("ix_agent_eval_cases_agent_id","agent_eval_cases",["agent_id"]);op.create_index("ix_agent_eval_cases_created_by","agent_eval_cases",["created_by"]);op.create_index("ix_agent_eval_case_tenant_agent","agent_eval_cases",["organization_id","agent_id"])
    op.create_table("agent_eval_runs",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("prompt_version_id",sa.Uuid(),sa.ForeignKey("agent_prompt_versions.id",ondelete="CASCADE"),nullable=False),sa.Column("run_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("score",sa.Integer(),nullable=False),sa.Column("passed",sa.Boolean(),nullable=False),sa.Column("total_cases",sa.Integer(),nullable=False),sa.Column("passed_cases",sa.Integer(),nullable=False),sa.Column("results",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_agent_eval_runs_organization_id","agent_eval_runs",["organization_id"]);op.create_index("ix_agent_eval_runs_prompt_version_id","agent_eval_runs",["prompt_version_id"]);op.create_index("ix_agent_eval_runs_run_by","agent_eval_runs",["run_by"]);op.create_index("ix_agent_eval_run_tenant_version","agent_eval_runs",["organization_id","prompt_version_id"])
def downgrade()->None:op.drop_table("agent_eval_runs");op.drop_table("agent_eval_cases");op.drop_table("agent_prompt_versions")
