"""Add privacy and LGPD center. Revision ID: 0027_privacy_lgpd Revises: 0026_agent_studio"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0027_privacy_lgpd";down_revision:str|None="0026_agent_studio";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("data_processing_activities",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(180),nullable=False),sa.Column("purpose",sa.Text(),nullable=False),sa.Column("legal_basis",sa.String(60),nullable=False),sa.Column("data_categories",sa.JSON(),nullable=False),sa.Column("data_subjects",sa.JSON(),nullable=False),sa.Column("recipients",sa.JSON(),nullable=False),sa.Column("retention_days",sa.Integer(),nullable=False),sa.Column("sensitive_data",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","name"));op.create_index("ix_data_processing_activities_organization_id","data_processing_activities",["organization_id"]);op.create_index("ix_data_processing_activities_created_by","data_processing_activities",["created_by"])
    op.create_table("consent_records",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("subject_identifier",sa.String(255),nullable=False),sa.Column("purpose",sa.String(240),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="granted"),sa.Column("source",sa.String(60),nullable=False),sa.Column("proof",sa.JSON(),nullable=False),sa.Column("granted_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revoked_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_consent_records_organization_id","consent_records",["organization_id"]);op.create_index("ix_consent_tenant_subject","consent_records",["organization_id","subject_identifier"])
    op.create_table("data_subject_requests",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("requested_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("processed_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("subject_name",sa.String(180),nullable=False),sa.Column("subject_identifier",sa.String(255),nullable=False),sa.Column("request_type",sa.String(30),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="open"),sa.Column("due_at",sa.DateTime(timezone=True),nullable=False),sa.Column("result",sa.JSON()),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_data_subject_requests_organization_id","data_subject_requests",["organization_id"]);op.create_index("ix_data_subject_requests_requested_by","data_subject_requests",["requested_by"]);op.create_index("ix_data_subject_requests_processed_by","data_subject_requests",["processed_by"]);op.create_index("ix_dsr_tenant_status","data_subject_requests",["organization_id","status"])
    op.create_table("retention_policies",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(160),nullable=False),sa.Column("resource_type",sa.String(80),nullable=False),sa.Column("retention_days",sa.Integer(),nullable=False),sa.Column("action",sa.String(30),nullable=False,server_default="anonymize"),sa.Column("legal_hold",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","resource_type"));op.create_index("ix_retention_policies_organization_id","retention_policies",["organization_id"]);op.create_index("ix_retention_policies_created_by","retention_policies",["created_by"])
def downgrade()->None:op.drop_table("retention_policies");op.drop_table("data_subject_requests");op.drop_table("consent_records");op.drop_table("data_processing_activities")
