"""Add incident and SLA center. Revision ID: 0028_incident_sla Revises: 0027_privacy_lgpd"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0028_incident_sla";down_revision:str|None="0027_privacy_lgpd";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("incident_alert_rules",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(160),nullable=False),sa.Column("source_type",sa.String(40),nullable=False),sa.Column("condition_type",sa.String(60),nullable=False),sa.Column("severity",sa.String(20),nullable=False,server_default="medium"),sa.Column("response_sla_minutes",sa.Integer(),nullable=False,server_default="60"),sa.Column("resolution_sla_minutes",sa.Integer(),nullable=False,server_default="480"),sa.Column("escalation_role",sa.String(30),nullable=False,server_default="manager"),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","name"));op.create_index("ix_incident_alert_rules_organization_id","incident_alert_rules",["organization_id"]);op.create_index("ix_incident_alert_rules_created_by","incident_alert_rules",["created_by"])
    op.create_table("operational_incidents",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("rule_id",sa.Uuid(),sa.ForeignKey("incident_alert_rules.id",ondelete="SET NULL")),sa.Column("assigned_to",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("source_type",sa.String(40),nullable=False),sa.Column("source_id",sa.String(120),nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("severity",sa.String(20),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="open"),sa.Column("response_due_at",sa.DateTime(timezone=True),nullable=False),sa.Column("resolution_due_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("resolved_at",sa.DateTime(timezone=True)),sa.Column("resolution_note",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","source_type","source_id"));op.create_index("ix_operational_incidents_organization_id","operational_incidents",["organization_id"]);op.create_index("ix_operational_incidents_rule_id","operational_incidents",["rule_id"]);op.create_index("ix_operational_incidents_assigned_to","operational_incidents",["assigned_to"]);op.create_index("ix_incident_tenant_status","operational_incidents",["organization_id","status"])
    op.create_table("incident_events",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("incident_id",sa.Uuid(),sa.ForeignKey("operational_incidents.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("event_type",sa.String(40),nullable=False),sa.Column("note",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_incident_events_organization_id","incident_events",["organization_id"]);op.create_index("ix_incident_events_incident_id","incident_events",["incident_id"]);op.create_index("ix_incident_events_user_id","incident_events",["user_id"]);op.create_index("ix_incident_event_tenant_incident","incident_events",["organization_id","incident_id"])
def downgrade()->None:op.drop_table("incident_events");op.drop_table("operational_incidents");op.drop_table("incident_alert_rules")
