"""Add notification center. Revision ID: 0029_notification_center Revises: 0028_incident_sla"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0029_notification_center";down_revision:str|None="0028_incident_sla";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("notification_templates",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(160),nullable=False),sa.Column("event_type",sa.String(80),nullable=False),sa.Column("channel",sa.String(30),nullable=False),sa.Column("subject_template",sa.String(240),nullable=False),sa.Column("body_template",sa.Text(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","event_type","channel"));op.create_index("ix_notification_templates_organization_id","notification_templates",["organization_id"]);op.create_index("ix_notification_templates_created_by","notification_templates",["created_by"])
    op.create_table("notification_preferences",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.Uuid(),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("event_type",sa.String(80),nullable=False),sa.Column("channel",sa.String(30),nullable=False),sa.Column("destination",sa.String(255)),sa.Column("enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","user_id","event_type","channel"));op.create_index("ix_notification_preferences_organization_id","notification_preferences",["organization_id"]);op.create_index("ix_notification_preferences_user_id","notification_preferences",["user_id"])
    op.create_table("operational_notifications",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("recipient_user_id",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("template_id",sa.Uuid(),sa.ForeignKey("notification_templates.id",ondelete="SET NULL")),sa.Column("event_type",sa.String(80),nullable=False),sa.Column("channel",sa.String(30),nullable=False),sa.Column("destination",sa.String(255)),sa.Column("title",sa.String(240),nullable=False),sa.Column("body",sa.Text(),nullable=False),sa.Column("priority",sa.String(20),nullable=False,server_default="normal"),sa.Column("status",sa.String(30),nullable=False,server_default="queued"),sa.Column("attempts",sa.Integer(),nullable=False,server_default="0"),sa.Column("idempotency_key",sa.String(180),nullable=False),sa.Column("metadata_json",sa.JSON(),nullable=False),sa.Column("last_error",sa.Text()),sa.Column("read_at",sa.DateTime(timezone=True)),sa.Column("delivered_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","idempotency_key"));op.create_index("ix_operational_notifications_organization_id","operational_notifications",["organization_id"]);op.create_index("ix_operational_notifications_recipient_user_id","operational_notifications",["recipient_user_id"]);op.create_index("ix_operational_notifications_template_id","operational_notifications",["template_id"]);op.create_index("ix_notification_tenant_status","operational_notifications",["organization_id","status"])
def downgrade()->None:op.drop_table("operational_notifications");op.drop_table("notification_preferences");op.drop_table("notification_templates")
