"""Add business continuity center. Revision ID: 0030_business_continuity Revises: 0029_notification_center"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0030_business_continuity";down_revision:str|None="0029_notification_center";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("backup_policies",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(160),nullable=False),sa.Column("scope",sa.String(40),nullable=False,server_default="configuration"),sa.Column("frequency_hours",sa.Integer(),nullable=False,server_default="24"),sa.Column("retention_days",sa.Integer(),nullable=False,server_default="30"),sa.Column("rpo_minutes",sa.Integer(),nullable=False,server_default="1440"),sa.Column("rto_minutes",sa.Integer(),nullable=False,server_default="240"),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","name"));op.create_index("ix_backup_policies_organization_id","backup_policies",["organization_id"]);op.create_index("ix_backup_policies_created_by","backup_policies",["created_by"])
    op.create_table("backup_snapshots",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("policy_id",sa.Uuid(),sa.ForeignKey("backup_policies.id",ondelete="CASCADE"),nullable=False),sa.Column("triggered_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("status",sa.String(30),nullable=False),sa.Column("encrypted_payload",sa.Text(),nullable=False),sa.Column("manifest",sa.JSON(),nullable=False),sa.Column("checksum",sa.String(64),nullable=False),sa.Column("size_bytes",sa.Integer(),nullable=False),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_backup_snapshots_organization_id","backup_snapshots",["organization_id"]);op.create_index("ix_backup_snapshots_policy_id","backup_snapshots",["policy_id"]);op.create_index("ix_backup_snapshots_triggered_by","backup_snapshots",["triggered_by"]);op.create_index("ix_backup_snapshot_tenant_created","backup_snapshots",["organization_id","created_at"])
    op.create_table("restore_drills",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("snapshot_id",sa.Uuid(),sa.ForeignKey("backup_snapshots.id",ondelete="CASCADE"),nullable=False),sa.Column("initiated_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("target_environment",sa.String(40),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("recovery_time_seconds",sa.Integer(),nullable=False),sa.Column("integrity_passed",sa.Boolean(),nullable=False),sa.Column("notes",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)));op.create_index("ix_restore_drills_organization_id","restore_drills",["organization_id"]);op.create_index("ix_restore_drills_snapshot_id","restore_drills",["snapshot_id"]);op.create_index("ix_restore_drills_initiated_by","restore_drills",["initiated_by"]);op.create_index("ix_restore_drill_tenant_created","restore_drills",["organization_id","created_at"])
def downgrade()->None:op.drop_table("restore_drills");op.drop_table("backup_snapshots");op.drop_table("backup_policies")
