"""Add compliance center. Revision ID: 0031_compliance_center Revises: 0030_business_continuity"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0031_compliance_center";down_revision:str|None="0030_business_continuity";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("compliance_programs",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(160),nullable=False),sa.Column("framework",sa.String(40),nullable=False),sa.Column("owner_role",sa.String(30),nullable=False,server_default="admin"),sa.Column("status",sa.String(30),nullable=False,server_default="active"),sa.Column("target_date",sa.Date()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","framework"));op.create_index("ix_compliance_programs_organization_id","compliance_programs",["organization_id"]);op.create_index("ix_compliance_programs_created_by","compliance_programs",["created_by"])
    op.create_table("compliance_controls",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("program_id",sa.Uuid(),sa.ForeignKey("compliance_programs.id",ondelete="CASCADE"),nullable=False),sa.Column("code",sa.String(40),nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("category",sa.String(80),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("evidence_source",sa.String(60),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="not_assessed"),sa.Column("score",sa.Integer(),nullable=False,server_default="0"),sa.Column("finding",sa.Text()),sa.Column("last_assessed_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("program_id","code"));op.create_index("ix_compliance_controls_organization_id","compliance_controls",["organization_id"]);op.create_index("ix_compliance_controls_program_id","compliance_controls",["program_id"]);op.create_index("ix_compliance_control_tenant_status","compliance_controls",["organization_id","status"])
    op.create_table("compliance_reports",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("program_id",sa.Uuid(),sa.ForeignKey("compliance_programs.id",ondelete="CASCADE"),nullable=False),sa.Column("generated_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("readiness_score",sa.Integer(),nullable=False),sa.Column("summary",sa.JSON(),nullable=False),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_compliance_reports_organization_id","compliance_reports",["organization_id"]);op.create_index("ix_compliance_reports_program_id","compliance_reports",["program_id"]);op.create_index("ix_compliance_reports_generated_by","compliance_reports",["generated_by"]);op.create_index("ix_compliance_report_tenant_created","compliance_reports",["organization_id","created_at"])
def downgrade()->None:op.drop_table("compliance_reports");op.drop_table("compliance_controls");op.drop_table("compliance_programs")
