"""Add implementation and go-live center. Revision ID: 0032_implementation_go_live Revises: 0031_compliance_center"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0032_implementation_go_live";down_revision:str|None="0031_compliance_center";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("implementation_projects",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("owner_user_id",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(180),nullable=False),sa.Column("customer_segment",sa.String(60),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="planning"),sa.Column("starts_on",sa.Date(),nullable=False),sa.Column("target_go_live",sa.Date(),nullable=False),sa.Column("go_live_at",sa.DateTime(timezone=True)),sa.Column("progress_percent",sa.Integer(),nullable=False,server_default="0"),sa.Column("implementation_fee_cents",sa.Integer(),nullable=False,server_default="0"),sa.Column("notes",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_implementation_projects_organization_id","implementation_projects",["organization_id"]);op.create_index("ix_implementation_projects_created_by","implementation_projects",["created_by"]);op.create_index("ix_implementation_projects_owner_user_id","implementation_projects",["owner_user_id"]);op.create_index("ix_implementation_tenant_status","implementation_projects",["organization_id","status"])
    op.create_table("implementation_milestones",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("project_id",sa.Uuid(),sa.ForeignKey("implementation_projects.id",ondelete="CASCADE"),nullable=False),sa.Column("title",sa.String(180),nullable=False),sa.Column("category",sa.String(60),nullable=False),sa.Column("position",sa.Integer(),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="pending"),sa.Column("due_date",sa.Date()),sa.Column("completed_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("evidence_note",sa.Text()),sa.UniqueConstraint("project_id","position"));op.create_index("ix_implementation_milestones_organization_id","implementation_milestones",["organization_id"]);op.create_index("ix_implementation_milestones_project_id","implementation_milestones",["project_id"]);op.create_index("ix_implementation_milestones_completed_by","implementation_milestones",["completed_by"]);op.create_index("ix_milestone_tenant_status","implementation_milestones",["organization_id","status"])
    op.create_table("go_live_assessments",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("project_id",sa.Uuid(),sa.ForeignKey("implementation_projects.id",ondelete="CASCADE"),nullable=False),sa.Column("assessed_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("readiness_score",sa.Integer(),nullable=False),sa.Column("approved",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("checks",sa.JSON(),nullable=False),sa.Column("blockers",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_go_live_assessments_organization_id","go_live_assessments",["organization_id"]);op.create_index("ix_go_live_assessments_project_id","go_live_assessments",["project_id"]);op.create_index("ix_go_live_assessments_assessed_by","go_live_assessments",["assessed_by"]);op.create_index("ix_go_live_assessment_tenant_created","go_live_assessments",["organization_id","created_at"])
def downgrade()->None:op.drop_table("go_live_assessments");op.drop_table("implementation_milestones");op.drop_table("implementation_projects")
