"""Add value and ROI center. Revision ID: 0033_value_roi Revises: 0032_implementation_go_live"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0033_value_roi";down_revision:str|None="0032_implementation_go_live";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("value_baselines",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("name",sa.String(180),nullable=False),sa.Column("department",sa.String(80),nullable=False),sa.Column("period",sa.String(7),nullable=False),sa.Column("monthly_process_hours",sa.Integer(),nullable=False),sa.Column("hourly_cost_cents",sa.Integer(),nullable=False),sa.Column("monthly_operational_cost_cents",sa.Integer(),nullable=False),sa.Column("monthly_revenue_cents",sa.Integer(),nullable=False),sa.Column("leads_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("conversions_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("organization_id","name"));op.create_index("ix_value_baselines_organization_id","value_baselines",["organization_id"]);op.create_index("ix_value_baselines_created_by","value_baselines",["created_by"])
    op.create_table("value_measurements",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("baseline_id",sa.Uuid(),sa.ForeignKey("value_baselines.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("period",sa.String(7),nullable=False),sa.Column("monthly_process_hours",sa.Integer(),nullable=False),sa.Column("monthly_operational_cost_cents",sa.Integer(),nullable=False),sa.Column("monthly_revenue_cents",sa.Integer(),nullable=False),sa.Column("operai_cost_cents",sa.Integer(),nullable=False),sa.Column("leads_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("conversions_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("hours_saved",sa.Integer(),nullable=False),sa.Column("cost_savings_cents",sa.Integer(),nullable=False),sa.Column("incremental_revenue_cents",sa.Integer(),nullable=False),sa.Column("net_benefit_cents",sa.Integer(),nullable=False),sa.Column("roi_percent",sa.Integer(),nullable=False),sa.Column("payback_days",sa.Integer()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("baseline_id","period"));op.create_index("ix_value_measurements_organization_id","value_measurements",["organization_id"]);op.create_index("ix_value_measurements_baseline_id","value_measurements",["baseline_id"]);op.create_index("ix_value_measurements_created_by","value_measurements",["created_by"]);op.create_index("ix_value_measurement_tenant_period","value_measurements",["organization_id","period"])
    op.create_table("value_reports",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("measurement_id",sa.Uuid(),sa.ForeignKey("value_measurements.id",ondelete="CASCADE"),nullable=False),sa.Column("generated_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("headline",sa.String(240),nullable=False),sa.Column("executive_summary",sa.JSON(),nullable=False),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_value_reports_organization_id","value_reports",["organization_id"]);op.create_index("ix_value_reports_measurement_id","value_reports",["measurement_id"]);op.create_index("ix_value_reports_generated_by","value_reports",["generated_by"]);op.create_index("ix_value_report_tenant_created","value_reports",["organization_id","created_at"])
def downgrade()->None:op.drop_table("value_reports");op.drop_table("value_measurements");op.drop_table("value_baselines")
