"""Add strategy and OKR center. Revision ID: 0034_strategy_okrs Revises: 0033_value_roi"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0034_strategy_okrs";down_revision:str|None="0033_value_roi";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("strategic_objectives",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("owner_user_id",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("title",sa.String(200),nullable=False),sa.Column("perspective",sa.String(40),nullable=False),sa.Column("period",sa.String(20),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="active"),sa.Column("progress_percent",sa.Integer(),nullable=False,server_default="0"),sa.Column("expected_value_cents",sa.Integer(),nullable=False,server_default="0"),sa.Column("realized_value_cents",sa.Integer(),nullable=False,server_default="0"),sa.Column("starts_on",sa.Date(),nullable=False),sa.Column("ends_on",sa.Date(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_strategic_objectives_organization_id","strategic_objectives",["organization_id"]);op.create_index("ix_strategic_objectives_created_by","strategic_objectives",["created_by"]);op.create_index("ix_strategic_objectives_owner_user_id","strategic_objectives",["owner_user_id"]);op.create_index("ix_objective_tenant_status","strategic_objectives",["organization_id","status"])
    op.create_table("strategic_key_results",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("objective_id",sa.Uuid(),sa.ForeignKey("strategic_objectives.id",ondelete="CASCADE"),nullable=False),sa.Column("title",sa.String(220),nullable=False),sa.Column("metric_name",sa.String(100),nullable=False),sa.Column("unit",sa.String(30),nullable=False),sa.Column("baseline_value",sa.Integer(),nullable=False),sa.Column("target_value",sa.Integer(),nullable=False),sa.Column("current_value",sa.Integer(),nullable=False),sa.Column("progress_percent",sa.Integer(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("objective_id","title"));op.create_index("ix_strategic_key_results_organization_id","strategic_key_results",["organization_id"]);op.create_index("ix_strategic_key_results_objective_id","strategic_key_results",["objective_id"]);op.create_index("ix_key_result_tenant_status","strategic_key_results",["organization_id","status"])
    op.create_table("strategic_initiatives",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("objective_id",sa.Uuid(),sa.ForeignKey("strategic_objectives.id",ondelete="CASCADE"),nullable=False),sa.Column("agent_id",sa.Uuid(),sa.ForeignKey("agents.id",ondelete="SET NULL")),sa.Column("owner_user_id",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("title",sa.String(200),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("priority",sa.String(20),nullable=False),sa.Column("expected_value_cents",sa.Integer(),nullable=False),sa.Column("realized_value_cents",sa.Integer(),nullable=False),sa.Column("due_date",sa.Date()),sa.Column("risk_note",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_strategic_initiatives_organization_id","strategic_initiatives",["organization_id"]);op.create_index("ix_strategic_initiatives_objective_id","strategic_initiatives",["objective_id"]);op.create_index("ix_strategic_initiatives_agent_id","strategic_initiatives",["agent_id"]);op.create_index("ix_strategic_initiatives_owner_user_id","strategic_initiatives",["owner_user_id"]);op.create_index("ix_initiative_tenant_status","strategic_initiatives",["organization_id","status"])
def downgrade()->None:op.drop_table("strategic_initiatives");op.drop_table("strategic_key_results");op.drop_table("strategic_objectives")
