"""Add executive decision room. Revision ID: 0035_decision_room Revises: 0034_strategy_okrs"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision:str="0035_decision_room";down_revision:str|None="0034_strategy_okrs";branch_labels:str|Sequence[str]|None=None;depends_on:str|Sequence[str]|None=None
def upgrade()->None:
    op.create_table("decision_cases",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("objective_id",sa.Uuid(),sa.ForeignKey("strategic_objectives.id",ondelete="SET NULL")),sa.Column("created_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("decided_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("title",sa.String(200),nullable=False),sa.Column("context",sa.Text(),nullable=False),sa.Column("decision_type",sa.String(40),nullable=False),sa.Column("urgency",sa.String(20),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("selected_option_id",sa.Uuid()),sa.Column("decision_note",sa.Text()),sa.Column("due_at",sa.DateTime(timezone=True)),sa.Column("decided_at",sa.DateTime(timezone=True)),sa.Column("review_due_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_decision_cases_organization_id","decision_cases",["organization_id"]);op.create_index("ix_decision_cases_objective_id","decision_cases",["objective_id"]);op.create_index("ix_decision_cases_created_by","decision_cases",["created_by"]);op.create_index("ix_decision_cases_decided_by","decision_cases",["decided_by"]);op.create_index("ix_decision_cases_selected_option_id","decision_cases",["selected_option_id"]);op.create_index("ix_decision_case_tenant_status","decision_cases",["organization_id","status"])
    op.create_table("decision_options",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("case_id",sa.Uuid(),sa.ForeignKey("decision_cases.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("expected_impact_cents",sa.Integer(),nullable=False),sa.Column("implementation_cost_cents",sa.Integer(),nullable=False),sa.Column("risk_score",sa.Integer(),nullable=False),sa.Column("confidence_score",sa.Integer(),nullable=False),sa.Column("time_to_value_days",sa.Integer(),nullable=False),sa.Column("score",sa.Integer(),nullable=False),sa.Column("assumptions",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("case_id","name"));op.create_index("ix_decision_options_organization_id","decision_options",["organization_id"]);op.create_index("ix_decision_options_case_id","decision_options",["case_id"]);op.create_index("ix_decision_option_tenant_score","decision_options",["organization_id","score"])
    op.create_table("decision_reviews",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("organization_id",sa.Uuid(),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("case_id",sa.Uuid(),sa.ForeignKey("decision_cases.id",ondelete="CASCADE"),nullable=False),sa.Column("reviewed_by",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("outcome",sa.String(30),nullable=False),sa.Column("realized_impact_cents",sa.Integer(),nullable=False),sa.Column("lessons",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_decision_reviews_organization_id","decision_reviews",["organization_id"]);op.create_index("ix_decision_reviews_case_id","decision_reviews",["case_id"]);op.create_index("ix_decision_reviews_reviewed_by","decision_reviews",["reviewed_by"]);op.create_index("ix_decision_review_tenant_created","decision_reviews",["organization_id","created_at"])
def downgrade()->None:op.drop_table("decision_reviews");op.drop_table("decision_options");op.drop_table("decision_cases")
